name: Build LaTeX document

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'mathcomp/mathcomp:1.12.0-coq-8.13'
      fail-fast: false
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile Coq-Doc
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          before_script: |
            startGroup "Create Makefile.coq and add permission"
              make || true
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "Build documentation"
              make -j2 html
            endGroup
          uninstall: |
            startGroup "Clean"
              make clean
            endGroup
      - name: Revert Coq user permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: hydras.tex
          working_directory: doc
          latexmk_use_lualatex: true

      - name: Extract PDF and Coq-Doc
        run: |
          mkdir -p public/doc public/theories
          cp doc/hydras.pdf public/doc/
          cp -r theories/html public/theories/ || true
      # Depending on whether we are on master or not, we deploy to
      # GitHub Pages or as an artifact
      - name: Deploy to GitHub pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: public
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy artifact
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          path: public
