name: Build LaTeX document and Coq-Doc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Build coqdoc and Alectryon movies
        uses: coq-community/docker-coq-action@v1
        with:
          # We cannot use the math-comp images because the OCaml version is too old
          coq_version: '8.13'
          ocaml_version: '4.07-flambda'
          before_script: |
            startGroup "Install Alectryon"
              sudo apt-get update
              yes | sudo apt-get install python3-pip
              yes | sudo pip3 install alectryon
              opam install coq-serapi -y
            endGroup
            startGroup "Add permissions"
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "Build Coq files"
              make -j "$(nproc)"
            endGroup
            startGroup "Build Alectryon movies"
              make -C doc/movies -j "$(nproc)" all
            endGroup
            startGroup "Build coqdoc documentation"
              make -j "$(nproc)" html
            endGroup
          uninstall: |
            startGroup "Clean"
              make clean
            endGroup

      - name: Revert Coq user permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: hydras.tex
          working_directory: doc
          latexmk_use_lualatex: true

      - name: Extract PDF and Coq-Doc
        run: |
          mkdir -p public/doc public/theories
          cp doc/hydras.pdf public/doc/
          cp -r theories/html public/theories/
      # Depending on whether we are on master or not, we deploy to
      # GitHub Pages or as an artifact
      - name: Deploy to GitHub pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: public
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy artifact
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          path: public
